version: '3.7'

services:
  opensearch:
    container_name: opensearch
    image: docker.io/opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=Developer@123"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  dashboards:
    container_name: opensearch-dashboards
    image: docker.io/opensearchproject/opensearch-dashboards:latest
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    ports:
      - "5601:5601"
    networks:
      - opensearch-net

  data-prepper:
    container_name: data-prepper
    image: opensearchproject/data-prepper:2
    depends_on:
      - opensearch
    volumes:
      # multi-pipeline config
      - ./log_pipelines.yaml:/usr/share/data-prepper/pipelines/log_pipelines.yaml
      # base server config
      - ./data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    environment:
      # Tell Data Prepper which pipeline config file to load
      - DATA_PREPPER_PIPELINE_FILE=/usr/share/data-prepper/pipelines/log_pipelines.yaml
    ports:
      - "2021:2021"
    networks:
      - opensearch-net

  fluent-bit:
    container_name: fluent-bit
    image: docker.io/fluent/fluent-bit
    depends_on:
      - data-prepper
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      # Mount host logs into container.
      # If you're on Linux/WSL, /var/log exists and this will work.
      # On Windows, replace /var/log with a specific path or generated log dir.
      - /var/log:/host/var/log:ro
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
